console.log("\nMMMMMMMMMMMMMMM".white)
console.log("MMMMMMMMMMMMMMM".white)
console.log("MMMMM".white)
console.log("MMMMM".white)
console.log("MMMMMMMMMMMMMMM".white)
console.log("MMMMMMMMMMMMMMM".white)
console.log("MMMNM".white + "          __  ______  _     ___ ___ _____        _ ____".white      )
console.log("MMMNM".white + "          \\ \\/ /  _ \\| |   / _ \\_ _|_   _|      | / ___|".white )
console.log("MMMNM".white + "           \\  /| |_) | |  | | | | |  | |     _  | \\___ \\".white  )
console.log("MMMMMMMMMMMMMMM".white + " /  \\|  __/| |__| |_| | |  | |    | |_| |___) |".white   )
console.log("MMMMMMMMMMMMMMM".white + "/_/\\_\\_|   |_____\\___/___| |_| []  \\___/|____/".white  )